services:
  frontend:
    build:
      context: ./client     
      dockerfile: Dockerfile
    ports:
      - "8080:80"           
    depends_on:
      - backend             
    networks:
      - app-network

  backend:
    build:
      context: ./server     
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
