name: Trigger auto deployment for beyond-earth-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/beyond-earth-backend-AutoDeployTrigger-afd3ccf9-2750-45bc-8eb5-fae5baabe6be.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BEYONDEARTHBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BEYONDEARTHBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BEYONDEARTHBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.BEYONDEARTHBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BEYONDEARTHBACKEND_REGISTRY_PASSWORD }}
          containerAppName: beyond-earth-backend
          resourceGroup: beyond-earth
          imageToBuild: moaazemam88/beyond-earth-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


